[Fix] message変数名変更
nodeがconst 変数のscopeを正しく認識してくれなくて
SyntaxError: Identifier 'message' has already been declared
となっていた。